// <auto-generated />
using Biblioteca;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Biblioteca.Migrations
{
    [DbContext(typeof(BibliotecaContext))]
    partial class BibliotecaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("AutorLibro", b =>
                {
                    b.Property<int>("AutoresId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LibrosId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AutoresId", "LibrosId");

                    b.HasIndex("LibrosId");

                    b.ToTable("LibrosAutores", (string)null);

                    b.HasData(
                        new
                        {
                            AutoresId = 1,
                            LibrosId = 1
                        },
                        new
                        {
                            AutoresId = 2,
                            LibrosId = 2
                        },
                        new
                        {
                            AutoresId = 3,
                            LibrosId = 3
                        },
                        new
                        {
                            AutoresId = 4,
                            LibrosId = 3
                        },
                        new
                        {
                            AutoresId = 1,
                            LibrosId = 4
                        });
                });

            modelBuilder.Entity("Biblioteca.Autor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Autores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "J.R.R. Tolkien",
                            Pais = "Reino Unido"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Brandon Sanderson",
                            Pais = "Estados Unidos"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Neil Gaiman",
                            Pais = "Reino Unido"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Terry Pratchett",
                            Pais = "Reino Unido"
                        });
                });

            modelBuilder.Entity("Biblioteca.Libro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Anio")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Libros");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Anio = 1954,
                            ISBN = "978-0261103252",
                            Titulo = "El Señor de los Anillos"
                        },
                        new
                        {
                            Id = 2,
                            Anio = 2006,
                            ISBN = "978-8466656948",
                            Titulo = "El Imperio Final"
                        },
                        new
                        {
                            Id = 3,
                            Anio = 1990,
                            ISBN = "978-8445077926",
                            Titulo = "Buenos Presagios"
                        },
                        new
                        {
                            Id = 4,
                            Anio = 1937,
                            ISBN = "978-0261102217",
                            Titulo = "El Hobbit"
                        });
                });

            modelBuilder.Entity("AutorLibro", b =>
                {
                    b.HasOne("Biblioteca.Autor", null)
                        .WithMany()
                        .HasForeignKey("AutoresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Biblioteca.Libro", null)
                        .WithMany()
                        .HasForeignKey("LibrosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
