// <auto-generated />
using System;
using EntityFramework2505;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EntityFramework2505.Migrations
{
    [DbContext(typeof(TiendaContext))]
    [Migration("20260526072301_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("EntityFramework2505.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Dispositivos electrónicos y gadgets.",
                            Nombre = "Electrónica"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Prendas de vestir para todas las edades.",
                            Nombre = "Ropa"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Artículos para el hogar y decoración.",
                            Nombre = "Hogar"
                        });
                });

            modelBuilder.Entity("EntityFramework2505.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Precio")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaId = 1,
                            Descripcion = "Teléfono inteligente de última generación.",
                            FechaCreacion = new DateTime(2026, 5, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Smartphone",
                            Precio = 699.99m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 2,
                            CategoriaId = 1,
                            Descripcion = "Portátil potente para trabajo y entretenimiento.",
                            FechaCreacion = new DateTime(2026, 5, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Laptop",
                            Precio = 1299.99m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 3,
                            CategoriaId = 2,
                            Descripcion = "Camiseta de algodón para uso diario.",
                            FechaCreacion = new DateTime(2026, 5, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Camiseta",
                            Precio = 19.99m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 4,
                            CategoriaId = 3,
                            Descripcion = "Sofá cómodo para sala de estar.",
                            FechaCreacion = new DateTime(2026, 5, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Sofá",
                            Precio = 499.99m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 5,
                            CategoriaId = 3,
                            Descripcion = "Lámpara de mesa moderna para iluminación ambiental.",
                            FechaCreacion = new DateTime(2026, 5, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Lámpara de mesa",
                            Precio = 89.99m,
                            Stock = 40
                        },
                        new
                        {
                            Id = 6,
                            CategoriaId = 1,
                            Descripcion = "Auriculares inalámbricos con cancelación de ruido.",
                            FechaCreacion = new DateTime(2026, 5, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Auriculares",
                            Precio = 199.99m,
                            Stock = 25
                        });
                });

            modelBuilder.Entity("EntityFramework2505.Producto", b =>
                {
                    b.HasOne("EntityFramework2505.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("EntityFramework2505.Categoria", b =>
                {
                    b.Navigation("Productos");
                });
#pragma warning restore 612, 618
        }
    }
}
